name: hearing_aid
description: 

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  speech_to_text: ^3.1.0
  rflutter_alert: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/

  uses-material-design: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

